### ISSUE TITLE
Evaluation result is false should not be redirect to os.Stderr 

### ISSUE THREAD

**Issue by SoulKyu** [ahrtr/etcd-defrag#35]
Actually when you start the etcd-defrag if the fragmentation is not performed due to a specific defrag-rule, the log indicating which indicate this will be forwarded to Stderr.

It is not an error so it shouldn't be redirected to Stderr, but probably more into Stdout.

here is the related go line : https://github.com/ahrtr/etcd-defrag/blob/88a7fdd70511796ea3e3d4b10d4430173c4288d0/main.go#L141

I can create a PR if you think its ok !

**Comment by ahrtr** [comment]
Thanks, Please feel free to raise a PR.

**Comment by ahrtr** [comment]
Resolved in https://github.com/ahrtr/etcd-defrag/pull/36
