### ISSUE TITLE
Adding new variables in defragmentation rule/Adding 

### ISSUE THREAD

**Issue by CaojiamingAlan** [ahrtr/etcd-defrag#5]
I think it will be convenient if we add the following defragmentation rule variables, so that we don't need to write expressions manually:
dbQuotaUsage = dbSize/dbQuota
dbSizeUnused = dbSize - dbSizeInUse

I can make a pull request to work on these.

**Comment by ahrtr** [comment]
Thanks @CaojiamingAlan for raising this. 

It makes sense to me. Only one minor comment, I think the naming `dbSizeFree` is a little better than `dbSizeUnused`. There is no suffix "ed" in "dbSizeInUse", it's a little inconsistent if we use `dbSizeUnused`.

Please feel free to deliver a PR. thx

**Comment by ahrtr** [comment]
Resolved in https://github.com/ahrtr/etcd-defrag/pull/6
